### ISSUE TITLE
help: How to integrate and start rmf in real scenarios

### ISSUE THREAD

**Issue by liugehaizaixue** [open-rmf/rmf#248]
I read most of the documentation, which is based on the demo world. 
However, if I want to use real scenes and real robot fleet to achieve this, what should I do? 
For example, how to start "rmf" without gazebo? 
Is there any relevant document or case?

**Comment by mxgrey** [comment]
Generally speaking, cases of real deployments are kept private because they contain sensitive information like the floor plans of actual buildings. For that reason, I can't think of any link I can point you at to show an example of a real deployment configuration.

That said, the difference between running in simulation vs real robots is simply about which adapters (i.e. fleet adapters, door adapters, lift adapter) are being launched. The adapters launched in `rmf_demos` are designed to talk to the simulated devices that are in Gazebo. [Real world adapters](https://github.com/open-rmf/awesome_adapters) are designed to talk to real world devices. To move from a simulated world to a real world, you mostly just need to substitute the simulation adapters with the relevant real world adapters in your launch files.

There are likely to be other complications in a real-world deployment, like configuring your network and configuring DDS, but those requirements are outside the scope of the RMF software.

Since this is not an issue, I'll be closing this ticket. If you want to discuss this further, I recommend using the [Discussion board](https://github.com/open-rmf/rmf/discussions).

**Comment by mxgrey** [comment]
You could also take a look at the [`rmf_deployment_template`](https://github.com/open-rmf/rmf_deployment_template/) which may address some questions or concerns that you are facing.
