### ISSUE TITLE
[Other issue]: rmf_traffic_schedule crash

### ISSUE THREAD

**Issue by sabbysim** [open-rmf/rmf#422]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

rmf_demo office fail to launch with the following error code:

[rmf_traffic_schedule-1] [FATAL] [1706509151.310826378] [rmf_traffic_schedule_primary]: Failed to correctly load participant registry: yaml-cpp: error at line 9, column 16: bad conversion
[rmf_traffic_schedule-1] 
[rmf_traffic_schedule-1] terminate called after throwing an instance of 'std::exception'
[rmf_traffic_schedule-1]   what():  std::exception
.
.
[ERROR] [rmf_traffic_schedule-1]: process has died [pid 115816, exit code -6, cmd '/home/krms/kj_ws/install/rmf_traffic_ros2/lib/rmf_traffic_ros2/rmf_traffic_schedule --ros-args -r __node:=rmf_traffic_schedule_primary --params-file /tmp/launch_params_pnrvbg7u'].

I tried both binary and build from source but error persists.
I am using Humble-release and the default launch command shown below:
ros2 launch rmf_demos_gz_classic office.launch.xml 

Tried changing the DDS as recommended by https://github.com/open-rmf/rmf/issues/258#issue-1418137613 but did not resolve the error.

I have the same configurations running on another PC but did not see this error. Have you experienced this intermittent error?

Full log shown below:
https://gist.github.com/mxgrey/0e0bb9aa2ff62de02be9e3c6f9aad02f

**Comment by mxgrey** [comment]
In the future please use gist.github.com to upload large walls of terminal output.

The pertinent log output is [this one](https://gist.github.com/mxgrey/0e0bb9aa2ff62de02be9e3c6f9aad02f#file-log-txt-L26):

```
[rmf_traffic_schedule-1] [FATAL] [1706509151.310826378] [rmf_traffic_schedule_primary]: Failed to correctly load participant registry: yaml-cpp: error at line 9, column 16: bad conversion
```

To help us debug the root cause of the problem, you can run follow these steps:


1. Begin a new gist by opening gist.github.com
2. In a terminal, navigate to the directory that you launch RMF from
3. Run this command: `$ cat .rmf_schedule_node.yaml | xclip -sel clip`
4. Ctrl-V into the blank gist that you began in step (1)
5. Click the arrow on this button to select "Create public gist"
![gist](https://github.com/open-rmf/rmf/assets/1307217/f48d3c93-5672-4433-9d27-0696ac31c652)

Then copy/paste a link to your gist into a comment here.

Once you've done all the above steps, you can run `$ rm .rmf_schedule_node.yaml` in the same directory that you launch RMF from. After you've done that, the problem should be gone.

**Comment by sabbysim** [comment]
@mxgrey, I reformatted the PC before I seeing your reply. The problem is gone now. 
Am I right to say that .rmf_schedule_node.yaml was corrupted? Just FYI, I upgraded to Ubuntu 22.04, installed humble and deleted galactic before the error happened.

**Comment by mxgrey** [comment]
Right the error had to do with failing to parse that file. If we could've seen its contents then maybe we could identify a cause for how it got into a bad state and implement a fix.
