### ISSUE TITLE
RMF Integration with ROS1 Navigation Stack using Free Fleet

### ISSUE THREAD

**Issue by sachinkum0009** [open-rmf/rmf#67]
## Environment
- OS Version: Ubuntu 20.04
- Binary Install Foxy and Noetic

## Description
- I want to integrate the [RMF with ROS1 Navigation Stack using Free Fleet](https://osrf.github.io/ros2multirobotbook/integration_free-fleet.html)
- I followed the documentation and able to integrate the free fleet with ros1 navigation stack. (able to send the goal to navigation stack using the free_fleet)
- But when i launch the rmf, it is sending the same path request to free_fleet hence the free_fleet is sending the same goal to move_base.

Can you please help and guide me for this issue :pray:  ?

**Comment by mxgrey** [comment]
This is more of a discussion topic than an issue, so I'm going to close this.

Is this similar to the discussion that was already opened here? https://github.com/open-rmf/rmf/discussions/63

If so, I suggest continuing the discussion there. Otherwise you can open a new discussion for your particular concern.

**Comment by sachinkum0009** [comment]
Ok, thank you, will continue the discussion at #63
